Repository AIOCodeBase/GFGPOTD, pull requests merged in 2023-01, with the labels that each got.

#465 03 & 04 January 2023
  January 2023/03 January 2023/C++/Minimize number of Students to be removed.cpp
  January 2023/03 January 2023/Java/Minimize number of Students to be removed.java
  January 2023/03 January 2023/Python/Minimize number of Students to be removed.py
  January 2023/03 January 2023/README.md
  January 2023/04 January 2023/C++/Maximum Profit By Choosing A Subset Of Intervals.cpp
  January 2023/04 January 2023/Java/Maximum Profit By Choosing A Subset Of Intervals.java
  January 2023/04 January 2023/Python/Maximum Profit By Choosing A Subset Of Intervals.py
  January 2023/04 January 2023/README.md
Labels: documentation, enhancement, C++, Java, Python3

#466 05 January 2023
  January 2023/05 January 2023/C++/Find the longest string.cpp
  January 2023/05 January 2023/Java/Find the longest string.java
  January 2023/05 January 2023/Python/Find the longest string.py
  January 2023/05 January 2023/README.md
Labels: documentation, enhancement, C++, Java, Python3

#467 06 January 2023 - Shortest Prime Path
  January 2023/06 January 2023/C++/Shortest Prime Path.cpp
  January 2023/06 January 2023/Java/Shortest Prime Path.java
  January 2023/06 January 2023/Python/Shortest Prime Path.py
  January 2023/06 January 2023/README.md
Labels: documentation, enhancement, C++, Java, Python3

#468 07 January 2023 - Flattening a Linked List
  January 2023/07 January 2023/C++/Flattening a Linked List.cpp
  January 2023/07 January 2023/Java/Flattening a Linked List.java
  January 2023/07 January 2023/Python/Flattening a Linked List.py
  January 2023/07 January 2023/README.md
Labels: documentation, enhancement, C++, Java, Python3

#469 Absolute difference divisible by K & Last modified ball
  January 2023/08 January 2023/C++/Absolute difference divisible by K.cpp
  January 2023/08 January 2023/Java/Absolute difference divisible by K.java
  January 2023/08 January 2023/Python/Absolute difference divisible by K.py
  January 2023/08 January 2023/README.md
  January 2023/09 January 2023/C++/Last modified ball.cpp
  January 2023/09 January 2023/Java/Last modified ball.java
  January 2023/09 January 2023/Python/Last modified ball.py
  January 2023/09 January 2023/README.md
  January 2023/README.md
Labels: documentation, enhancement, C++, Java, Python3

#470 10 January 2023 - Transform to Sum Tree
  January 2023/10 January 2023/C++/Transform to Sum Tree.cpp
  January 2023/10 January 2023/Java/Transform to Sum Tree.java
  January 2023/10 January 2023/Python/Transform to Sum Tree.py
  January 2023/10 January 2023/README.md
Labels: documentation, enhancement, C++, Java, Python3

#511 11 January 2023 - Make array elements unique
  January 2023/11 January 2023/C++/Make array elements unique.cpp
  January 2023/11 January 2023/Java/Make array elements unique.java
  January 2023/11 January 2023/Python/Make array elements unique.py
  January 2023/11 January 2023/README.md
Labels: documentation, enhancement, C++, Java, Python3

#514 12 January 2023 - Minimize the sum.py
  January 2023/12 January 2023/.py
  January 2023/12 January 2023/Minimize the sum.py
Labels: Python3

#515 Update README.md
  README.md
Labels: documentation, enhancement

#517 Readme file added 12 JAN
  January 2023/12 January 2023/README.md
Labels: documentation, enhancement

#516 12 Jan code added CPP
  January 2023/12 January 2023/.cpp
Labels: enhancement, C++

#519 New Enhancement & Workflow
  .github/CODEOWNERS
  README.md
Labels: documentation, enhancement

#520 Update README.md
  README.md
Labels: documentation, enhancement

#521 Update README.md
  January 2023/13 January 2023/README.md
Labels: documentation, enhancement

#522 Count Lucky Permutations.cpp code added.
  January 2023/13 January 2023/.cpp
  January 2023/13 January 2023/Count Lucky Permutations.cpp
Labels: enhancement, C++

#526 12 January 2023 - Added Python & Java code
  .gitignore
  January 2023/13 January 2023/.java
  January 2023/13 January 2023/.py
  January 2023/13 January 2023/Count Lucky Permutations.java
  January 2023/13 January 2023/Count Lucky Permutations.py
Labels: enhancement, Java, Python3

#527 14 January 2023 - Maximum Number of Toys.py
  January 2023/14 January 2023/.py
  January 2023/14 January 2023/Maximum Number of Toys.py
Labels: enhancement, Python3

#525 Maximum Number of Toys.java code added
  January 2023/14 January 2023/.java
  January 2023/14 January 2023/Maximum Number of Toys.java
Labels: enhancement, Java

#528 14JAN code added
  January 2023/14 January 2023/.cpp
  January 2023/14 January 2023/Maximum Number of Toys.cpp
Labels: enhancement, C++

#529 readme file added
  January 2023/14 January 2023/README.md
Labels: documentation, enhancement

#570 15 January 2023 - Count the Substring.py
  January 2023/15 January 2023/.py
  January 2023/15 January 2023/Count the Substring.py
Labels: enhancement, Python3

#571 15Jan Java code added
  January 2023/15 January 2023/.java
  January 2023/15 January 2023/Count the Substring.java
Labels: enhancement, Java

#573 15JAN file added
  January 2023/15 January 2023/.cpp
  January 2023/15 January 2023/Count the Substring.cpp
Labels: enhancement, C++

#574 Readme file for 15 JAN added
  January 2023/15 January 2023/README.md
Labels: documentation, enhancement

#575 16 January 2023 - Next Greater Element.js
  January 2023/16 January 2023/Next Greater Element.js
Labels: enhancement, JavaScript

#576 21 & 22 January 2023
  January 2023/21 January 2023/.cpp
  January 2023/21 January 2023/.java
  January 2023/21 January 2023/.py
  January 2023/21 January 2023/README.md
  January 2023/22 January 2023/.cpp
  January 2023/22 January 2023/.java
  January 2023/22 January 2023/.py
  January 2023/22 January 2023/README.md
Labels: enhancement

#577 23, 24, 25, 26, 27, 28, 29, 30 & 31 January 2023
  January 2023/23 January 2023/.cpp
  January 2023/23 January 2023/.java
  January 2023/23 January 2023/.py
  January 2023/23 January 2023/README.md
  January 2023/24 January 2023/.cpp
  January 2023/24 January 2023/.java
  January 2023/24 January 2023/.py
  January 2023/24 January 2023/README.md
  January 2023/25 January 2023/.cpp
  January 2023/25 January 2023/.java
  January 2023/25 January 2023/.py
  January 2023/25 January 2023/README.md
  January 2023/26 January 2023/.cpp
  January 2023/26 January 2023/.java
  January 2023/26 January 2023/.py
  January 2023/26 January 2023/README.md
  January 2023/27 January 2023/.cpp
  January 2023/27 January 2023/.java
  January 2023/27 January 2023/.py
  January 2023/27 January 2023/README.md
  January 2023/28 January 2023/.cpp
  January 2023/28 January 2023/.java
  January 2023/28 January 2023/.py
  January 2023/28 January 2023/README.md
  January 2023/29 January 2023/.cpp
  January 2023/29 January 2023/.java
  January 2023/29 January 2023/.py
  January 2023/29 January 2023/README.md
  January 2023/30 January 2023/.cpp
  January 2023/30 January 2023/.java
  January 2023/30 January 2023/.py
  January 2023/30 January 2023/README.md
  January 2023/31 January 2023/.cpp
  January 2023/31 January 2023/.java
  January 2023/31 January 2023/.py
  January 2023/31 January 2023/README.md
Labels: enhancement

#582 CPP file 16 JAN added
  January 2023/16 January 2023/.cpp
  January 2023/16 January 2023/Next Greater Element.cpp
Labels: enhancement, C++

#583 16Jan Java code added
  January 2023/16 January 2023/.java
  January 2023/16 January 2023/Next Greater Element.java
Labels: enhancement, Java

#584 README FILE ADDED 16 JAN
  January 2023/16 January 2023/README.md
Labels: documentation, enhancement

#585 Added Next Greater Element code in python
  January 2023/16 January 2023/.py
  January 2023/16 January 2023/Next Greater Element.py
Labels: enhancement, Python3

#586 17Jan Java code added
  January 2023/17 January 2023/.java
  January 2023/17 January 2023/Find the maximum GCD of the siblings of a Binary Tree.java
Labels: enhancement, Java

#588 17 JAN README FILE
  January 2023/17 January 2023/README.md
Labels: documentation, enhancement

#589 Python code added
  January 2023/17 January 2023/.py
  January 2023/17 January 2023/Find the maximum GCD of the siblings of a Binary Tree.py
Labels: enhancement, Python3

#590 18Jan Java code added
  January 2023/18 January 2023/.java
  January 2023/18 January 2023/Find the first node of loop in linked list.java
Labels: enhancement, Java

#591 18Jan README added
  January 2023/18 January 2023/README.md
Labels: documentation, enhancement

#593 Python code added 18jan
  January 2023/18 January 2023/.py
  January 2023/18 January 2023/Find the first node of loop in linked list.py
Labels: enhancement, Python3

#587 17JAN C++ CODE added
  January 2023/17 January 2023/.cpp
  January 2023/17 January 2023/Find the maximum GCD of the siblings of a Binary Tree.cpp
Labels: enhancement, C++

#594 19Jan Java code added
  January 2023/19 January 2023/.java
  January 2023/19 January 2023/Carpet into Box.java
Labels: enhancement, Java

#596 19JAN code added
  January 2023/19 January 2023/.cpp
  January 2023/19 January 2023/Carpet into Box.cpp
Labels: enhancement, C++

#597 19 January 2023 - Carpet into Box.py
  January 2023/19 January 2023/.py
  January 2023/19 January 2023/Carpet into Box.py
Labels: enhancement, Python3

#598 20Jan README added
  January 2023/20 January 2023/README.md
Labels: documentation, enhancement

#599 20JAN CPP code added
  January 2023/20 January 2023/.cpp
  January 2023/20 January 2023/Maximum Weight Node.cpp
Labels: enhancement, C++

#600 Python code added
  January 2023/20 January 2023/.py
  January 2023/20 January 2023/Maximum Weight Node.py
Labels: enhancement, Python3

#601 java code added
  January 2023/20 January 2023/.java
  January 2023/20 January 2023/Maximum Weight Node.java
Labels: enhancement, Java

#602 21Jan README added
  January 2023/21 January 2023/README.md
Labels: documentation, enhancement

#603 21Jan C++ code added
  January 2023/21 January 2023/.cpp
  January 2023/21 January 2023/Minimum X (xor) A.cpp
Labels: enhancement, C++

#604 21Jan Java code added
  January 2023/21 January 2023/.java
  January 2023/21 January 2023/Minimum X (xor) A.java
Labels: enhancement, Java

#605 Python code added 21JAN
  January 2023/21 January 2023/.py
  January 2023/21 January 2023/Minimum X (xor) A.py
Labels: enhancement, Python3

#606 22Jan README added
  January 2023/22 January 2023/README.md
Labels: documentation, enhancement

#607 22Jan C++ code added
  January 2023/22 January 2023/.cpp
  January 2023/22 January 2023/GCD Array.cpp
Labels: enhancement, C++

#608 22Jan Java code added
  January 2023/22 January 2023/.java
  January 2023/22 January 2023/GCD Array.java
Labels: enhancement, Java

#609 Update and rename .py to GCD Array.py
  January 2023/22 January 2023/.py
  January 2023/22 January 2023/GCD Array.py
Labels: enhancement, Python3

#611 23Jan README added
  January 2023/23 January 2023/README.md
Labels: documentation, enhancement

#612 23Jan C++ code added
  January 2023/23 January 2023/.cpp
  January 2023/23 January 2023/Geeks And The String.cpp
Labels: enhancement, C++

#613 23Jan Java code added
  January 2023/23 January 2023/.java
  January 2023/23 January 2023/Geeks And The String.java
Labels: enhancement, Java

#614 python code added
  January 2023/23 January 2023/.py
  January 2023/23 January 2023/Geeks And The String.py
Labels: enhancement, Python3

#615 24Jan README added
  January 2023/24 January 2023/README.md
Labels: documentation, enhancement

#616 24Jan C++ code added
  January 2023/24 January 2023/.cpp
  January 2023/24 January 2023/Convert an array to reduced form.cpp
Labels: enhancement, c++

#617 24Jan Java code added
  January 2023/24 January 2023/.java
  January 2023/24 January 2023/Convert an array to reduced form.java
Labels: enhancement, java

#619 Python code added
  January 2023/24 January 2023/.py
  January 2023/24 January 2023/Convert an array to reduced form.py
Labels: enhancement, python3

#620 25Jan Java code added
  January 2023/25 January 2023/.java
  January 2023/25 January 2023/Type it!.java
Labels: enhancement, java

#621 25Jan README added
  January 2023/25 January 2023/README.md
Labels: documentation, enhancement

#622 25Jan C++ code added
  January 2023/25 January 2023/.cpp
  January 2023/25 January 2023/Type it!.cpp
Labels: enhancement, c++

#623 PYTHON CODE ADDED
  January 2023/25 January 2023/.py
  January 2023/25 January 2023/Type it!.py
Labels: documentation, enhancement

#624 Python code added
  January 2023/26 January 2023/.py
  January 2023/26 January 2023/Case-specific Sorting of Strings.py
Labels: enhancement, python3

#625 JAVA CODE ADDED
  January 2023/26 January 2023/.java
  January 2023/26 January 2023/Case-specific Sorting of Strings.java
Labels: enhancement, java

#626 Create Case-specific Sorting of Strings.js
  January 2023/26 January 2023/Case-specific Sorting of Strings.js
Labels: enhancement, javascript

#627 26Jan README added
  January 2023/26 January 2023/README.md
Labels: documentation, enhancement

#628 26Jan C++ code added
  January 2023/26 January 2023/.cpp
  January 2023/26 January 2023/Case-specific Sorting of Strings.cpp
Labels: enhancement, c++

#629 27Jan README added
  January 2023/27 January 2023/README.md
Labels: documentation, enhancement

#630 27Jan Java code added
  January 2023/27 January 2023/.java
  January 2023/27 January 2023/Total Decoding Messages.java
Labels: enhancement, java

#631 27Jan C++ code added
  January 2023/27 January 2023/.cpp
  January 2023/27 January 2023/Total Decoding Messages.cpp
Labels: enhancement, c++

#636 27 January 2023 - Total Decoding Messages.py
  January 2023/27 January 2023/.py
  January 2023/27 January 2023/Total Decoding Messages.py
Labels: enhancement, python3

#632 28Jan README added
  January 2023/28 January 2023/README.md
Labels: documentation, enhancement

#633 28Jan Java code added
  January 2023/28 January 2023/.java
  January 2023/28 January 2023/Scrambled String.java
Labels: enhancement, java

#634 28Jan C++ code added
  January 2023/28 January 2023/.cpp
  January 2023/28 January 2023/Scrambled String.cpp
Labels: enhancement, c++

#635 Python code added 28 jan
  January 2023/28 January 2023/.py
Labels: enhancement, python3

#638 29Jan README added
  January 2023/29 January 2023/README.md
Labels: documentation, enhancement

#639 29Jan C++ code added
  January 2023/29 January 2023/.cpp
  January 2023/29 January 2023/Min operations.cpp
Labels: enhancement, c++

#637 JAVA CODE ADDED 29JAN
  January 2023/29 January 2023/.java
  January 2023/29 January 2023/Min operations.java
Labels: enhancement, java

#640 Update .gitignore
  .gitignore
Labels: enhancement

#641 Update .gitignore
  .gitignore
Labels: enhancement

#642 Update .gitignore
  .gitignore
Labels: enhancement

#643 Code added 29 JAN python
  January 2023/29 January 2023/.py
  January 2023/29 January 2023/Min operations.py
Labels: enhancement, python3

#645 30Jan C++ code added
  January 2023/30 January 2023/.cpp
  January 2023/30 January 2023/Select Nodes.cpp
Labels: enhancement, c++

#644 30Jan README added
  January 2023/30 January 2023/README.md
Labels: documentation, enhancement
